#!/bin/sh
#$ -S /bin/bash
#$ -cwd
#$ -l epyc
#$ -l s_vmem=4G,mem_req=4G
#$ -N a01
#$ -pe def_slot 16
#$ -l d_rt=2:00:00
#$ -l s_rt=2:00:00
#$ -o ./log
#$ -e ./log

TARGETFILES=($(ls inputs | grep fastq))
TARGETFILE=${TARGETFILES[0]}
TARGETID=$(basename ${TARGETFILES[0]} .fastq)
echo $TARGETID

source ~/.bashrc
TRIMMOMATIC="/usr/local/biotools/t/trimmomatic:0.39--hdfd78af_2"

singularity exec -B $PWD $TRIMMOMATIC /usr/local/bin/trimmomatic \
  SE \
  -threads 16 \
  -phred33 \
  inputs/${TARGETFILE} \
  preprocessing/${TARGETID}_trim3.fastq \
  ILLUMINACLIP:/home/edge2992/myprojects/PARIS/icSHAPE/data/adapter/TruSeq2-SE.fa:3:20:10 \
  SLIDINGWINDOW:10:30 \
  MINLEN:28 \
  -trimlog preprocessing/trim3log.txt \
  -summary preprocessing/${TARGETID}_trim3summary.txt

  # icSHAPE/data/adapter/TruSeq2-SE.fa \
# Truseq2 GA2 machines
# 許容ミスマッチ2,palindrome clip threshold 30 simple ciup threshold 4
# LEADINGはリードの先頭からクオリティスコアが13未満の塩基を切り捨てる
# TRAILINGはリードの末端からクオリティスコアが0未満の塩基を切り捨てる(おそらく切り捨てない)
# MINLENは25塩基を満たないリードを除去する




