#!/bin/sh
#$ -S /bin/bash
#$ -cwd
#$ -N a01dg
#$ -l epyc
#$ -l s_vmem=32G,mem_req=32G
#$ -pe def_slot 1
#$ -o ./log
#$ -e ./log

PARISPATH="/lustre7/home/edge2992/myprojects/PARIS/paris"

TARGETFILE=($(ls samtools | grep prim_N))
TARGETPREFIX=$(basename ${TARGETFILE} Aligned_prim_N.out_sorted.sam)
mm10genome="/lustre7/home/edge2992/ref/mm10/Mus_musculus.GRCm38.dna.primary_assembly.fa"
mm10annotation="/lustre7/home/edge2992/ref/mm10/Mus_musculus.GRCm38.95.gtf"
# mm10chromsize="/lustre7/home/edge2992/ref/mm10/STAR_reference/chrLength.txt"
mm10chromsize="/lustre7/home/edge2992/ref/mm10/STAR_reference/chrNameLength.txt"

echo $TARGETFILE
echo $TARGETPREFIX

# conda activate paris

perl ${PARISPATH}/samPairingCalling.test.pl \
  -i samtools/${TARGETFILE} \
  -j star2/${TARGETPREFIX}Chimeric.out.junction \
  -s star2/${TARGETPREFIX}Chimeric.out.sam \
  -o ${TARGETPREFIX}_geometric \
  -g $mm10genome \
  -z $mm10chromsize \
  -t $mm10genome \
  -l 15 -p 2 -c geometric \
  # 1> log/${TARGETPREFIX}_geometric.stdout \
  # 2> log/${TARGETPREFIX}_geometric.log

